### PR TITLE
Spark encoder approach

### PR DESCRIPTION
**Pull request by metasim**
This is not a working example, but does exhibit progress by a) using the `Encoder` API, b) properly constructing `ExpressionEncoder` to enable translation within the Spark Catalyst engine, and c) uses Databricks `spark-avro` library for schema and content translation.

The problem is that the result is getting corrupted when the `GenericRow` output from the Databricks conversion is further translated by the Spark `RowEncoder` API, which is hard to debug because a) it uses runtime generated code to do the transformation, and b) it is using `sun.misc.Unsafe`-based APIs to store the row data, making it almost impossible to inspect without doing pointer math. 

Currently, converting this:

    TemporalProjectedExtent(Extent(0.0, 0.0, 8.0, 10.0), LatLng, ZonedDateTime.now())

to a Dataframe results in what looks like bit/byte offset errors in interpretation:

```
+--------------------------------------------------------+----+------------+
|extent                                                  |epsg|instant     |
+--------------------------------------------------------+----+------------+
|[6.79038653307E-313,2.1373E-320,7.344291429133E-312,0.0]|0   |137438953512|
+--------------------------------------------------------+----+------------+
```

Will continue trying out options, but the going is slow and there's still a lot to learn about the `Expression` API that all this is dependent upon.

If anyone is willing, a code review for the purposes of generating ideas for further investigation is appreciated.

CC: @pomadchin @echeipesh  @lossyrob @jnh5y

### CODE REVIEW

**Review by jnh5y — COMMENTED** [review]
@metasim Generally, I'm only grokking part of it.  At a high level, this seems reasonable.  

I'd be interested to see what all needs to be registered with Catalyst in terms of functions and types to sort out a working SQL example.

**Comment by metasim** [comment]
@jnh5y At this point the hope is to be dealing with just native types, given that we're relying on an approach whereby the user has already provided a mapping between the GT types and an Avro schema. I agree that longer term having a native GT representation will be beneficial, it's somewhat of an evolutionary leap beyond what I'm trying to do here, which is make use of existing infrastructure to get data out of GT RDDs and into a dataframe with minimal fuss. The expectation is that the user would then have to apply additional dataframe transformations themselves to get it into the form wanted by SparkML. That said, I am learning more about the internals of Catalyst than I expected, and am getting glimmers of what you guys have done in GM.

PS: Thanks for taking a look!

**Comment by metasim** [comment]
w00t! Last update results in correct expansion:

```
+------------------+----+-------------+
|extent            |epsg|instant      |
+------------------+----+-------------+
|[0.0,0.0,8.0,10.0]|4326|1486562704426|
+------------------+----+-------------+
```

**Comment by metasim** [comment]
## Current status

### Input

```
(TemporalProjectedExtent(Extent(xmin, ymin, xmax, ymax), LatLng, ZonedDateTime.now()), MultibandTile(ByteArrayTile(...), ByteArrayTile(...), ByteArrayTile(...))) 
```

### Schema

```
root
 |-- _1: struct (nullable = false)
 |    |-- extent: struct (nullable = false)
 |    |    |-- xmin: double (nullable = false)
 |    |    |-- ymin: double (nullable = false)
 |    |    |-- xmax: double (nullable = false)
 |    |    |-- ymax: double (nullable = false)
 |    |-- epsg: integer (nullable = false)
 |    |-- instant: long (nullable = false)
 |-- _2: struct (nullable = false)
 |    |-- bands: array (nullable = false)
 |    |    |-- element: struct (containsNull = false)
 |    |    |    |-- member0: struct (nullable = true)
 |    |    |    |    |-- cols: integer (nullable = false)
 |    |    |    |    |-- rows: integer (nullable = false)
 |    |    |    |    |-- cells: binary (nullable = false)
 |    |    |    |    |-- noDataValue: integer (nullable = true)
 |    |    |    |-- member1: struct (nullable = true)
 |    |    |    |    |-- cols: integer (nullable = false)
 |    |    |    |    |-- rows: integer (nullable = false)
 |    |    |    |    |-- cells: array (nullable = false)
 |    |    |    |    |    |-- element: float (containsNull = false)
 |    |    |    |    |-- noDataValue: struct (nullable = false)
 |    |    |    |    |    |-- member0: boolean (nullable = true)
 |    |    |    |    |    |-- member1: float (nullable = true)
 |    |    |    |-- member2: struct (nullable = true)
 |    |    |    |    |-- cols: integer (nullable = false)
 |    |    |    |    |-- rows: integer (nullable = false)
 |    |    |    |    |-- cells: array (nullable = false)
 |    |    |    |    |    |-- element: double (containsNull = false)
 |    |    |    |    |-- noDataValue: struct (nullable = false)
 |    |    |    |    |    |-- member0: boolean (nullable = true)
 |    |    |    |    |    |-- member1: double (nullable = true)
 |    |    |    |-- member3: struct (nullable = true)
 |    |    |    |    |-- cols: integer (nullable = false)
 |    |    |    |    |-- rows: integer (nullable = false)
 |    |    |    |    |-- cells: array (nullable = false)
 |    |    |    |    |    |-- element: integer (containsNull = false)
 |    |    |    |    |-- noDataValue: integer (nullable = true)
 |    |    |    |-- member4: struct (nullable = true)
 |    |    |    |    |-- cols: integer (nullable = false)
 |    |    |    |    |-- rows: integer (nullable = false)
 |    |    |    |    |-- cells: array (nullable = false)
 |    |    |    |    |    |-- element: integer (containsNull = false)
 |    |    |    |    |-- noDataValue: integer (nullable = true)
 |    |    |    |-- member5: struct (nullable = true)
 |    |    |    |    |-- cols: integer (nullable = false)
 |    |    |    |    |-- rows: integer (nullable = false)
 |    |    |    |    |-- cells: binary (nullable = false)
 |    |    |    |-- member6: struct (nullable = true)
 |    |    |    |    |-- cols: integer (nullable = false)
 |    |    |    |    |-- rows: integer (nullable = false)
 |    |    |    |    |-- cells: binary (nullable = false)
 |    |    |    |    |-- noDataValue: integer (nullable = true)
 |    |    |    |-- member7: struct (nullable = true)
 |    |    |    |    |-- cols: integer (nullable = false)
 |    |    |    |    |-- rows: integer (nullable = false)
 |    |    |    |    |-- cells: array (nullable = false)
 |    |    |    |    |    |-- element: integer (containsNull = false)
 |    |    |    |    |-- noDataValue: integer (nullable = true)
```

### Dataframe

```
+--------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|_1                                    |_2                                                                                                                                                                                                   |
+--------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|[[1.0,2.0,3.0,4.0],4326,1486572290856]|[WrappedArray([[3,3,[B@2bb31455,-128],null,null,null,null,null,null,null], [[3,3,[B@3c16528d,-128],null,null,null,null,null,null,null], [[3,3,[B@2e45a357,-128],null,null,null,null,null,null,null])]|
|[[2.0,3.0,4.0,5.0],4326,1486572290891]|[WrappedArray([[3,3,[B@389a5022,-128],null,null,null,null,null,null,null], [[3,3,[B@bb8ead8,-128],null,null,null,null,null,null,null], [[3,3,[B@5b44318,-128],null,null,null,null,null,null,null])]  |
|[[3.0,4.0,5.0,6.0],4326,1486572290891]|[WrappedArray([[3,3,[B@6e807e2,-128],null,null,null,null,null,null,null], [[3,3,[B@6c995c5d,-128],null,null,null,null,null,null,null], [[3,3,[B@203b953c,-128],null,null,null,null,null,null,null])] |
+--------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by metasim** [comment]
@lossyrob FYI, if you call `.toJSON.show(false)` you get this output, indicating to me that the nested structure is nicely maintained (and `null`s removed).

```
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|value                                                                                                                                                                                                                                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|{"bands":[{"member0":{"cols":3,"rows":3,"cells":"AwMDAwMDAwMD","noDataValue":-128}},{"member0":{"cols":3,"rows":3,"cells":"AwMDAwMDAwMD","noDataValue":-128}},{"member0":{"cols":3,"rows":3,"cells":"AwMDAwMDAwMD","noDataValue":-128}}]}|
|{"bands":[{"member0":{"cols":3,"rows":3,"cells":"BAQEBAQEBAQE","noDataValue":-128}},{"member0":{"cols":3,"rows":3,"cells":"BAQEBAQEBAQE","noDataValue":-128}},{"member0":{"cols":3,"rows":3,"cells":"BAQEBAQEBAQE","noDataValue":-128}}]}|
|{"bands":[{"member0":{"cols":3,"rows":3,"cells":"BQUFBQUFBQUF","noDataValue":-128}},{"member0":{"cols":3,"rows":3,"cells":"BQUFBQUFBQUF","noDataValue":-128}},{"member0":{"cols":3,"rows":3,"cells":"BQUFBQUFBQUF","noDataValue":-128}}]}|
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Pull request merged**
